stages:
  - deploy
  - test

variables:
  DOCKER_IMAGE_NAME: "registry.gitlab.com/dev-ops-group-x/flight-booking/airline_system"
  DOCKER_IMAGE_TAG: "1.0"

before_script:
  - echo "Install Docker..."
  - apt-get update -qy
  - apt-get install -y docker.io

deploy-job:
  stage: deploy
  script:
     - echo "Deploying Docker image..."
     - docker:19.03.14-dind pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG || true
     - docker:19.03.14-dind run -d -p 8080:8080 --name airline_container $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

test-job:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here

# Add more stages and jobs for additional CI/CD steps as needed
